#!/usr/bin/env bash

# TODO: make it a little prettier
print_header() {
  printf "\n\n\n\e[1;32m$1\n"
  printf "%*s\e[0m\n\n" $(tput cols) "" | tr ' ' _
}

do_install() {
  # TODO: get rid of apt
  sudo apt-get install $1
}

declare -a packages=(
  'zsh'
  'zsh-antigen'
  'tmux'
  'colortest'
)

# authenticate user
sudo -v

# packages
# TODO: submodules
print_header 'installing packages'
sudo apt-get update

for package in "${packages[@]}"
do
  do_install $package
done

# change shell to zsh
print_header 'changing shell'
chsh -s $(which zsh)

# symlink dots
print_header 'cloning existing dots into ~/.old_dots_backup and building symlinks'
./symlink-setup
