#!/usr/bin/env bash

#printf "%*s\e[0m\n\n" $(tput cols) "" | tr ' ' _
print_header() {
  printf "\n\e[1;32m$1\n\n\e[0m"
}

do_install() {
  # TODO: get rid of apt
  sudo apt-get install $1
}

declare -a packages=(
  'zsh'
  'zsh-antigen'
  'tmux'
  'colortest'
  'tree'
)

# authenticate user
sudo -v

# packages
# TODO: submodules
print_header 'installing packages:'
sudo apt-get update

for package in "${packages[@]}"
do
  do_install $package
done

# change shell to zsh
print_header 'changing shell:'
chsh -s $(which zsh)

# symlink dots
print_header 'cloning existing dots into ~/.old_dots_backup and building symlinks:'
./symlink-setup
