#!/usr/bin/env bash

print_header() {
  printf "\n\e[0;32m$1\n\n\e[0m"
}

declare -a packages=(
  'zsh'
  'tmux'
  'tree'
)

# authenticate user
sudo -v

# packages
print_header 'installing packages:'
case $(uname) in
  'Darwin')
    for package in "${packages[@]}"
    do
      brew install $package
    done
    ;;
  'Linux')
    sudo apt-get update
    sudo apt-get install colortest
    for package in "${packages[@]}"
    do
      sudo apt-get install $package
    done
    ;;
esac

# change shell to zsh
print_header 'changing shell:'
chsh -s $(which zsh)

# symlink dots
print_header 'cloning existing dots into ~/.old_dots_backup and building symlinks:'
./symlink-setup
