#!/usr/bin/env bash

backup_folder='.old_dots_backup'

_backup_file() {
  if [ -f "$HOME/$1" ]
  then
    cp "$HOME/$1" "$HOME/$backup_folder"
  fi
}

_build_symlink() {
  ln -fs "$source_folder/$1" $HOME
}

case $(uname) in
  'Darwin')
    source_folder="$(dirname $(greadlink -f $BASH_SOURCE))/src"
    ;;
  'Linux')
    source_folder="$(dirname $(readlink -f $0))/src"
    ;;
esac

declare -a files=(
  '.bashrc'
  '.bash_profile'
  '.tmux.conf'
  '.zshrc'
  '.aliases'
  '.functions'
  '.exports'
)

# backup and symlinking
if [ ! -d "$HOME/$backup_folder" ]; then
  mkdir "$HOME/$backup_folder"
fi

for file in "${files[@]}"
do
  _backup_file $file
  _build_symlink $file
  printf "$file symlinked to $HOME\n"
done
