#!/usr/bin/env bash

backup_folder='.old_dots_backup'

case $(uname) in
  'Darwin')
    source_folder="$(dirname $(greadlink -f $BASH_SOURCE))/src"
    ;;
  'Linux')
    source_folder="$(dirname $(readlink -f $0))/src"
    ;;
esac

declare -a files=(
  '.bashrc'
  '.bash_profile'
  '.tmux.conf'
  '.zshrc'
)

backup_file() {
  if [ -f "$HOME/$1" ]
  then
    cp "$HOME/$1" "$HOME/$backup_folder"
  fi
}

build_symlink() {
  ln -fs "$source_folder/$1" $HOME
}

# backup and symlinking
if [ ! -d "$HOME/$backup_folder" ]; then
  mkdir "$HOME/$backup_folder"
fi

for file in "${files[@]}"
do
  backup_file $file
  build_symlink $file
  printf "$file symlinked to $HOME\n"
done
