#!/usr/bin/env bash

backup_folder='.old_dots_backup'

declare -a files=(
  '.bashrc'
  '.bash_profile'
  '.tmux.conf'
  '.zshrc'
)

backup_file() {
  if [ -f "~/$1" ]
  then
    cp "$HOME/$1" "$HOME/$backup_folder"
  fi
}

build_symlink() {
  ln -fs "$(dirname $(readlink -f $0))/src/$1" "$HOME"
}

# backup and symlinking
if [ ! -d "$HOME/$backup_folder" ]; then
  mkdir "$HOME/$backup_folder"
fi

for file in "${files[@]}"
do
  backup_file $file
  build_symlink $file
  printf "$file symlinked to $HOME\n"
done
