#!/usr/bin/env bash

src_path="$(dirname $(greadlink -f $BASH_SOURCE))"

# remove last login message
touch ~/.hushlogin

# remove new line square brackets
defaults write com.apple.Terminal ShowLineMarks -int 0
